# Host: alcatraz (bare-metal graphical install)
#
# Community convention: each host gets its own directory under hosts/.
# The host's configuration.nix contains only settings specific to this
# machine: hostname, locale, timezone, and hardware. Shared
# configuration is imported from modules/.
#
# When forking this repo for a new machine, copy this directory, update
# the values below, and run `nixos-generate-config` to produce a new
# hardware-configuration.nix for your hardware.

{ config, pkgs, ... }:

{
  imports = [
    # Shared modules
    ../../modules/base.nix
    ../../modules/desktop.nix
    # Hardware scan results (machine-specific, generated by nixos-generate-config)
    ./hardware-configuration.nix
    # Bootloader (machine-specific, overwritten by the ISO installer)
    ./bootloader.nix
  ];

  # --- Host-specific settings (set by the person installing) ---

  # Hostname
  networking.hostName = "alcatraz";

  # Timezone and locale (set these to match your location)
  time.timeZone = "Europe/Amsterdam";

  i18n.defaultLocale = "en_US.UTF-8";

  i18n.extraLocaleSettings = {
    LC_ADDRESS = "nl_NL.UTF-8";
    LC_IDENTIFICATION = "nl_NL.UTF-8";
    LC_MEASUREMENT = "nl_NL.UTF-8";
    LC_MONETARY = "nl_NL.UTF-8";
    LC_NAME = "nl_NL.UTF-8";
    LC_NUMERIC = "nl_NL.UTF-8";
    LC_PAPER = "nl_NL.UTF-8";
    LC_TELEPHONE = "nl_NL.UTF-8";
    LC_TIME = "nl_NL.UTF-8";
  };
}
