# Host: alcatraz-iso (installer ISO image)
#
# Produces a bootable ISO containing the Alcatraz OS installer.
# Boot from USB, connect to the internet, then run:
#   alcatraz-install /dev/sdX
#
# Build with:
#   nix build ./src#iso
#
# Write to USB:
#   sudo dd bs=4M conv=fsync oflag=direct status=progress \
#     if=result/iso/nixos-*.iso of=/dev/sdX

{ pkgs, inputs, self, ... }:

let
  diskoCli = inputs.disko.packages.${pkgs.system}.disko;

  alcatraz-install = pkgs.writeShellScriptBin "alcatraz-install" ''
    set -euo pipefail

    if [ "$(id -u)" -ne 0 ]; then
      echo "Error: alcatraz-install must be run as root."
      exit 1
    fi

    DISK="''${1:-}"
    if [ -z "$DISK" ]; then
      echo "Alcatraz OS Installer"
      echo ""
      echo "Usage: alcatraz-install <disk>"
      echo "Example: alcatraz-install /dev/sda"
      echo ""
      echo "Available disks:"
      lsblk -d -o NAME,SIZE,MODEL | grep -v loop
      exit 1
    fi

    if [ ! -b "$DISK" ]; then
      echo "Error: $DISK is not a block device."
      exit 1
    fi

    if [ ! -d /sys/firmware/efi ]; then
      echo "Error: UEFI firmware not detected."
      echo "Alcatraz OS requires a UEFI-capable system."
      exit 1
    fi

    echo "=== Alcatraz OS Installer ==="
    echo ""
    echo "Target disk: $DISK"
    lsblk "$DISK"
    echo ""
    echo "WARNING: ALL DATA on $DISK will be erased."
    read -p "Type 'yes' to continue: " CONFIRM
    if [ "$CONFIRM" != "yes" ]; then
      echo "Aborted."
      exit 0
    fi

    echo ""
    echo "[1/4] Partitioning, formatting, and mounting $DISK..."
    disko --mode destroy,format,mount --disk main "$DISK" /etc/alcatraz/src/hosts/alcatraz-iso/disko-config.nix

    echo "[2/4] Copying configuration..."
    mkdir -p /mnt/etc/nixos
    cp -r /etc/alcatraz/* /mnt/etc/nixos/

    # Write UEFI bootloader config for the target system.
    # The repo ships a BIOS/GRUB bootloader.nix for the developer's machine;
    # overwrite it with systemd-boot to match the UEFI disk layout disko created.
    cat > /mnt/etc/nixos/src/hosts/alcatraz/bootloader.nix << 'BOOTLOADER'
    # Bootloader configuration (UEFI / systemd-boot)
    #
    # Generated by alcatraz-install. Edit to match your system.
    {
      boot.loader.systemd-boot.enable = true;
      boot.loader.efi.canTouchEfiVariables = true;
    }
    BOOTLOADER

    echo "[3/4] Detecting hardware..."
    nixos-generate-config --root /mnt --dir /tmp/hw-config
    cp /tmp/hw-config/hardware-configuration.nix \
      /mnt/etc/nixos/src/hosts/alcatraz/hardware-configuration.nix

    echo "[4/4] Installing Alcatraz OS (this will take a while)..."
    nixos-install --flake /mnt/etc/nixos/src#alcatraz

    echo ""
    echo "=== Installation complete ==="
    echo "Remove the installation media and reboot."
  '';

in
{
  environment.systemPackages = with pkgs; [
    alcatraz-install
    diskoCli
    vim
    git
    parted
    gptfdisk
  ];

  # Make the flake source available at /etc/alcatraz in the live environment
  environment.etc."alcatraz".source = self;

  # Use fast compression during development. For release builds, remove this
  # line to use the default xz compression (smaller file, slower build).
  isoImage.squashfsCompression = "gzip -Xcompression-level 1";
}
